version: '3.8'

services:
  sound_player:
    build: .
    container_name: player
    devices:
      - "/dev/snd:/dev/snd"
    group_add:
      - "audio"
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
        - ./resources:/app/resources
    environment:
      - DISPLAY
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
