version: '3.8'

services:
  sound_player:
    build: .
    restart: always
    container_name: player
    #image: syukurdoker/spoke:latest
    devices:
      - "/dev/snd:/dev/snd"
    group_add:
      - "audio"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./resources:/app/resources
    environment:
      - DISPLAY
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
